export const translateMap: Record<string, string> = {
  glass: '玻璃',
  Hopper: '漏斗',
  Chest: '箱子',
  oak_planks: '橡木木板',
  smooth_stone: '平滑石头',
  Stone_Slab: '石头台阶',
  stone: '石头',
  Stationary_Water: '静态水',
  white_wool: '白色羊毛',
  cobblestone: '圆石',
  lever: '拉杆',
  oak_trapdoor: '橡木活板门',
  tripwire_hook: '绊线钩',
  Stationary_Water006: '水',
};
